mediatek: mt7622: initialize watchdog after DDR init
Initializing the WDT before memory calibration breaks reboot at least
on some MT7622 boards like the Bananapi BPi-R64:
NOTICE:  BL2: v2.7(release):OpenWrt v2022-08-18-9c9c4994-2 (mt7622-emmc-2ddr)
NOTICE:  BL2: Built : 04:00:25, Aug 27 2022
ERROR:   Cannot find any pass-window
ERROR:   no DATLAT taps pass, DATLAT calibration fail!
ERROR:   DATLAT calibration fail, write back to  20!
ERROR:   EMI: complex R/W mem test failed: -2

Move watchdog initialization to happen only after memory initialization
has completed to avoid the problem.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>